// // fakeCustomerData.js

// export const fakeCustomers = [
//   {
//     id: 1,
//     username: "John Smith",
//     phoneNumber: "012 345 6789",
//     email: "john.smith@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 2,
//     username: "Emma Wilson",
//     phoneNumber: "023 456 7890",
//     email: "emma.w@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 3,
//     username: "Michael Chen",
//     phoneNumber: "034 567 8901",
//     email: "m.chen@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 4,
//     username: "Sarah Johnson",
//     phoneNumber: "045 678 9012",
//     email: "sarah.j@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 5,
//     username: "David Brown",
//     phoneNumber: "056 789 0123",
//     email: "d.brown@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 6,
//     username: "Lisa Anderson",
//     phoneNumber: "067 890 1234",
//     email: "l.anderson@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 7,
//     username: "James Wilson",
//     phoneNumber: "078 901 2345",
//     email: "j.wilson@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 8,
//     username: "Emily Davis",
//     phoneNumber: "089 012 3456",
//     email: "e.davis@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 9,
//     username: "Robert Taylor",
//     phoneNumber: "090 123 4567",
//     email: "r.taylor@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 10,
//     username: "Jennifer Lee",
//     phoneNumber: "012 234 5678",
//     email: "j.lee@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 11,
//     username: "William Martin",
//     phoneNumber: "023 345 6789",
//     email: "w.martin@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 12,
//     username: "Jessica White",
//     phoneNumber: "034 456 7890",
//     email: "j.white@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 13,
//     username: "Daniel Kim",
//     phoneNumber: "045 567 8901",
//     email: "d.kim@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 14,
//     username: "Michelle Park",
//     phoneNumber: "056 678 9012",
//     email: "m.park@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 15,
//     username: "Christopher Lee",
//     phoneNumber: "067 789 0123",
//     email: "c.lee@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 16,
//     username: "Amanda Clark",
//     phoneNumber: "078 890 1234",
//     email: "a.clark@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 17,
//     username: "Kevin Wang",
//     phoneNumber: "089 901 2345",
//     email: "k.wang@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 18,
//     username: "Rachel Green",
//     phoneNumber: "090 012 3456",
//     email: "r.green@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 19,
//     username: "Thomas Brown",
//     phoneNumber: "012 123 4567",
//     email: "t.brown@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 20,
//     username: "Nicole Adams",
//     phoneNumber: "023 234 5678",
//     email: "n.adams@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 21,
//     username: "Brian Wilson",
//     phoneNumber: "034 345 6789",
//     email: "b.wilson@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 22,
//     username: "Laura Martinez",
//     phoneNumber: "045 456 7890",
//     email: "l.martinez@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 23,
//     username: "Steven Johnson",
//     phoneNumber: "056 567 8901",
//     email: "s.johnson@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 24,
//     username: "Catherine Lee",
//     phoneNumber: "067 678 9012",
//     email: "c.lee2@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 25,
//     username: "Andrew Chen",
//     phoneNumber: "078 789 0123",
//     email: "a.chen@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 26,
//     username: "Rebecca Taylor",
//     phoneNumber: "089 890 1234",
//     email: "r.taylor2@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 27,
//     username: "Patrick Wong",
//     phoneNumber: "090 901 2345",
//     email: "p.wong@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 28,
//     username: "Sandra Miller",
//     phoneNumber: "012 012 3456",
//     email: "s.miller@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 29,
//     username: "George Davis",
//     phoneNumber: "023 123 4567",
//     email: "g.davis@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 30,
//     username: "Elizabeth Kim",
//     phoneNumber: "034 234 5678",
//     email: "e.kim@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 31,
//     username: "Richard Park",
//     phoneNumber: "045 345 6789",
//     email: "r.park@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 32,
//     username: "Margaret Lee",
//     phoneNumber: "056 456 7890",
//     email: "m.lee@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
//   {
//     id: 33,
//     username: "Joseph Chang",
//     phoneNumber: "067 567 8901",
//     email: "j.chang@email.com",
//     avatar: "/api/placeholder/40/40",
//     selected: false,
//   },
// ];
