// export const allProductData = [
//   {
//     id: 1,
//     image: "/wine-bottle.png",
//     name: "35 South",
//     price: "$25.00",
//     quantity: 12,
//     category: "Drink",
//     expiryDate: "2025-12-31",
//     status: 1,
//   },
//   {
//     id: 2,
//     image: "/wine-bottle.png",
//     name: "Red Label",
//     price: "$32.50",
//     quantity: 8,
//     category: "Drink",
//     expiryDate: "2025-06-22",
//     status: 1,
//   },
//   {
//     id: 3,
//     image: "/wine-bottle.png",
//     name: "Black Label",
//     price: "$45.99",
//     quantity: 5,
//     category: "Drink",
//     expiryDate: "2026-08-22",
//     status: 0,
//   },
//   {
//     id: 4,
//     image: "/wine-bottle.png",
//     name: "Johnnie Walker",
//     price: "$52.75",
//     quantity: 10,
//     category: "Drink",
//     expiryDate: "2025-11-10",
//     status: 1,
//   },
//   {
//     id: 5,
//     image: "/wine-bottle.png",
//     name: "Jack Daniel's",
//     price: "$38.25",
//     quantity: 15,
//     category: "Drink",
//     expiryDate: "2026-02-28",
//     status: 1,
//   },
//   {
//     id: 6,
//     image: "/food-item.png",
//     name: "Organic Pasta",
//     price: "$4.99",
//     quantity: 30,
//     category: "Food",
//     expiryDate: "2025-06-24",
//     status: 0,
//   },
//   {
//     id: 7,
//     image: "/food-item.png",
//     name: "Olive Oil",
//     price: "$12.50",
//     quantity: 20,
//     category: "Food",
//     expiryDate: "2026-05-10",
//     status: 1,
//   },
//   {
//     id: 8,
//     image: "/electronics.png",
//     name: "Wireless Earbuds",
//     price: "$89.99",
//     quantity: 25,
//     category: "Electronics",
//     expiryDate: "N/A",
//     status: 1,
//   },
//   {
//     id: 10,
//     image: "/electronics.png",
//     name: "Smart Watch",
//     price: "$199.99",
//     quantity: 15,
//     category: "Electronics",
//     expiryDate: "N/A",
//     status: 1,
//   },
//   {
//     id: 11,
//     image: "/clothing.png",
//     name: "Denim Jeans",
//     price: "$49.99",
//     quantity: 35,
//     category: "Clothing",
//     expiryDate: "N/A",
//     status: 1,
//   },
//   {
//     id: 12,
//     image: "/food-item.png",
//     name: "Chocolate Bar",
//     price: "$3.99",
//     quantity: 100,
//     category: "Food",
//     expiryDate: "2025-10-15",
//     status: 0,
//   },
//   {
//     id: 13,
//     image: "/wine-bottle.png",
//     name: "Grey Goose",
//     price: "$42.99",
//     quantity: 18,
//     category: "Drink",
//     expiryDate: "2026-07-20",
//     status: 1,
//   },
//   {
//     id: 14,
//     image: "/electronics.png",
//     name: "Bluetooth Speaker",
//     price: "$79.99",
//     quantity: 5,
//     category: "Electronics",
//     expiryDate: "N/A",
//     status: 0,
//   },
//   {
//     id: 15,
//     image: "/clothing.png",
//     name: "Hoodie",
//     price: "$34.99",
//     quantity: 40,
//     category: "Clothing",
//     expiryDate: "N/A",
//     status: 1,
//   },
//   {
//     id: 16,
//     image: "/food-item.png",
//     name: "Potato Chips",
//     price: "$2.99",
//     quantity: 75,
//     category: "Food",
//     expiryDate: "2025-09-30",
//     status: 0,
//   },
//   {
//     id: 17,
//     image: "/wine-bottle.png",
//     name: "Absolut Vodka",
//     price: "$29.99",
//     quantity: 28,
//     category: "Drink",
//     expiryDate: "2026-04-15",
//     status: 1,
//   },
//   {
//     id: 18,
//     image: "/electronics.png",
//     name: "Power Bank",
//     price: "$45.99",
//     quantity: 9,
//     category: "Electronics",
//     expiryDate: "N/A",
//     status: 0,
//   },
//   {
//     id: 19,
//     image: "/clothing.png",
//     name: "Running Shoes",
//     price: "$89.99",
//     quantity: 25,
//     category: "Clothing",
//     expiryDate: "N/A",
//     status: 1,
//   },
//   {
//     id: 20,
//     image: "/food-item.png",
//     name: "Cereal Box",
//     price: "$5.99",
//     quantity: 45,
//     category: "Food",
//     expiryDate: "2025-11-30",
//     status: 0,
//   },
//   {
//     id: 21,
//     image: "/wine-bottle.png",
//     name: "Corona Beer",
//     price: "$15.99",
//     quantity: 60,
//     category: "Drink",
//     expiryDate: "2025-12-15",
//     status: 1,
//   },
//   {
//     id: 22,
//     image: "/electronics.png",
//     name: "USB Cable",
//     price: "$9.99",
//     quantity: 100,
//     category: "Electronics",
//     expiryDate: "N/A",
//     status: 0,
//   },
//   {
//     id: 23,
//     image: "/clothing.png",
//     name: "Winter Jacket",
//     price: "$129.99",
//     quantity: 20,
//     category: "Clothing",
//     expiryDate: "N/A",
//     status: 1,
//   },
//   {
//     id: 24,
//     image: "/food-item.png",
//     name: "Energy Drink",
//     price: "$3.49",
//     quantity: 80,
//     category: "Drink",
//     expiryDate: "2025-08-30",
//     status: 0,
//   },
//   {
//     id: 25,
//     image: "/electronics.png",
//     name: "Webcam",
//     price: "$59.99",
//     quantity: 15,
//     category: "Electronics",
//     expiryDate: "N/A",
//     status: 1,
//   },
//   {
//     id: 26,
//     image: "/clothing.png",
//     name: "Baseball Cap",
//     price: "$19.99",
//     quantity: 45,
//     category: "Clothing",
//     expiryDate: "N/A",
//     status: 0,
//   },
//   {
//     id: 27,
//     image: "/food-item.png",
//     name: "Protein Bar",
//     price: "$2.99",
//     quantity: 120,
//     category: "Food",
//     expiryDate: "2025-10-01",
//     status: 1,
//   },
//   {
//     id: 28,
//     image: "/wine-bottle.png",
//     name: "Heineken",
//     price: "$13.99",
//     quantity: 48,
//     category: "Drink",
//     expiryDate: "2025-11-20",
//     status: 0,
//   },
//   {
//     id: 29,
//     image: "/electronics.png",
//     name: "Mouse Pad",
//     price: "$14.99",
//     quantity: 55,
//     category: "Electronics",
//     expiryDate: "N/A",
//     status: 1,
//   },
//   {
//     id: 9,
//     image: "/clothing.png",
//     name: "Cotton T-shirt",
//     price: "$19.99",
//     quantity: 50,
//     category: "Clothing",
//     expiryDate: "N/A",
//     status: 0,
//   },
// ];
