// Sample order data
export const sampleOrders = [
  {
    id: "ORD-001",
    name: "John Doe",
    payment: "Completed",
    date: "01-05-2023",
    type: "Online",
    status: "Delivered",
    total: "$120.00",
  },
  {
    id: "ORD-002",
    name: "Jane Smith",
    payment: "Pending",
    date: "02-05-2023",
    type: "In-store",
    status: "Pending",
    total: "$85.50",
  },
  {
    id: "ORD-003",
    name: "Robert Johnson",
    payment: "Completed",
    date: "03-05-2023",
    type: "Online",
    status: "Delivered",
    total: "$210.75",
  },
  {
    id: "ORD-004",
    name: "Emily Davis",
    payment: "Failed",
    date: "04-05-2023",
    type: "Online",
    status: "Canceled",
    total: "$150.25",
  },
  {
    id: "ORD-005",
    name: "Michael Wilson",
    payment: "Completed",
    date: "05-05-2023",
    type: "In-store",
    status: "Delivered",
    total: "$95.00",
  },
  {
    id: "ORD-006",
    name: "Sarah Brown",
    payment: "Completed",
    date: "06-05-2023",
    type: "Online",
    status: "Delivered",
    total: "$175.50",
  },
  {
    id: "ORD-007",
    name: "David Miller",
    payment: "Pending",
    date: "07-05-2023",
    type: "In-store",
    status: "Processing",
    total: "$130.25",
  },
  {
    id: "ORD-008",
    name: "Lisa Anderson",
    payment: "Completed",
    date: "08-05-2023",
    type: "Online",
    status: "Delivered",
    total: "$225.00",
  },
  {
    id: "ORD-009",
    name: "James Taylor",
    payment: "Failed",
    date: "09-05-2023",
    type: "Online",
    status: "Canceled",
    total: "$90.75",
  },
  {
    id: "ORD-010",
    name: "Emma White",
    payment: "Completed",
    date: "10-05-2023",
    type: "In-store",
    status: "Delivered",
    total: "$145.50",
  },
  {
    id: "ORD-011",
    name: "William Clark",
    payment: "Pending",
    date: "11-05-2023",
    type: "Online",
    status: "Processing",
    total: "$180.25",
  },
  {
    id: "ORD-012",
    name: "Olivia Martin",
    payment: "Completed",
    date: "12-05-2023",
    type: "In-store",
    status: "Delivered",
    total: "$135.00",
  },
  {
    id: "ORD-013",
    name: "Daniel Lee",
    payment: "Failed",
    date: "13-05-2023",
    type: "Online",
    status: "Canceled",
    total: "$195.75",
  },
  {
    id: "ORD-014",
    name: "Sophia Garcia",
    payment: "Completed",
    date: "14-05-2023",
    type: "Online",
    status: "Delivered",
    total: "$110.50",
  },
  {
    id: "ORD-015",
    name: "Matthew Rodriguez",
    payment: "Pending",
    date: "15-05-2023",
    type: "In-store",
    status: "Processing",
    total: "$165.25",
  },
  {
    id: "ORD-016",
    name: "Isabella Lopez",
    payment: "Completed",
    date: "16-05-2023",
    type: "Online",
    status: "Delivered",
    total: "$205.00",
  },
  {
    id: "ORD-017",
    name: "Alexander Hall",
    payment: "Failed",
    date: "17-05-2023",
    type: "Online",
    status: "Canceled",
    total: "$140.75",
  },
  {
    id: "ORD-018",
    name: "Victoria Young",
    payment: "Completed",
    date: "18-05-2023",
    type: "In-store",
    status: "Delivered",
    total: "$185.50",
  },
  {
    id: "ORD-019",
    name: "Benjamin King",
    payment: "Pending",
    date: "19-05-2023",
    type: "Online",
    status: "Processing",
    total: "$155.25",
  },
  {
    id: "ORD-020",
    name: "Mia Wright",
    payment: "Completed",
    date: "20-05-2023",
    type: "In-store",
    status: "Delivered",
    total: "$170.00",
  },
  {
    id: "ORD-021",
    name: "Christopher Scott",
    payment: "Failed",
    date: "21-05-2023",
    type: "Online",
    status: "Canceled",
    total: "$125.75",
  },
  {
    id: "ORD-022",
    name: "Ava Green",
    payment: "Completed",
    date: "22-05-2023",
    type: "Online",
    status: "Delivered",
    total: "$215.50",
  },
  {
    id: "ORD-023",
    name: "Joseph Baker",
    payment: "Pending",
    date: "23-05-2023",
    type: "In-store",
    status: "Processing",
    total: "$160.25",
  },
  {
    id: "ORD-024",
    name: "Charlotte Adams",
    payment: "Completed",
    date: "24-05-2023",
    type: "Online",
    status: "Delivered",
    total: "$190.00",
  },
  {
    id: "ORD-025",
    name: "Andrew Nelson",
    payment: "Failed",
    date: "25-05-2023",
    type: "Online",
    status: "Canceled",
    total: "$145.75",
  },
];
